### ISSUE TITLE
Remove tabindex=5000

### ISSUE THREAD

**Issue by ffoodd** [wp-seopress/wp-seopress#7]
Hi there!

Could you please remove `tabindex="5000"` on your cookie consent message banner, or at least provide a hook to filter its template?

By using a positive tabindex value, you're preventing keyboard users to reject cookies by making this banner the last focusable item in the page… This is very annoying.

Thanks for this awesome plugin ;)

**Comment by wp-seopress** [comment]
Hi!
Already fixed in SEOPress 3.3.7 (not release yet) with lower tabindex:

`<div class="seopress-user-consent seopress-user-consent-hide" tabindex="10"><p>'.$msg.'<button id="seopress-user-consent-accept" tabindex="11">'.$consent_btn.'</button><button id="seopress-user-consent-close" tabindex="12">'.__('X','wp-seopress').'</button></p></div>';`

I also add a filter to this.

**Comment by ffoodd** [comment]
Thanks, the filter will be very helpful :)
FYI, tabindex greater than 0 is considered as bad practice for accessibility, since it makes keyboard navigation unpredictable.

If this tabindex is meant to make the notice focusable, I'd recommend using `tabindex="0"` which makes it focusable without changing its order.
